version: '3.4'
services:
  proxy:
    build:
       context: .
       args:
           - http_proxy
           - https_proxy
    environment:
      - PROXY_SERVER_NAME=${PROXY_SERVER_NAME}
      - PROXY_IDP_HOSTNAME=${PROXY_IDP_HOSTNAME}
    volumes:
      - ${HUB_PATH}/config/proxy/sp-cert.pem:/etc/shibboleth/sp-cert.pem
      - ${HUB_PATH}/config/proxy/sp-key.pem:/etc/shibboleth/sp-key.pem
      - ${HUB_PATH}/config/proxy/conf-environment:/usr/local/apache2/conf/conf.d/environment
