version: '3.0'
services:
  proxy:
    build:
       context: .
       args:
           - http_proxy
           - https_proxy
    environment:
      - PROXY_SERVER_NAME=${PROXY_SERVER_NAME}
      - PROXY_IDP_HOSTNAME=${PROXY_IDP_HOSTNAME}
